### ISSUE TITLE
Error when using /clerk command

### ISSUE THREAD

**Issue by TheGeek007** [remremrem/HyperMerchant#3]
I'm doing some testing to see if this mod would be good for our Pixelmon server.

I'm encountering an error when trying to use the /clerk command: Pastebin: http:pastebin.com/mEabQuzM

HyperMerchant Version: 1.56.1

HyperConomy Version: v0.974.56

cauldron-1.7.10-1.1207.01.198-server (craftbukkit/forge server)

It was working at some point, but can't get it to work again. Please tell me my next step! Thanks!

TheGeek007

**Comment by remremrem** [comment]
Thank you for reporting the error. Please try HyperMerchant development build #98 and let me know if that fixes it.

**Comment by TheGeek007** [comment]
Yes! This appears to fix the issue! Thanks for the rapid fix!
