### ISSUE TITLE
1.9 HyperMerchant Enchantment Bug

### ISSUE THREAD

**Issue by akarras** [remremrem/HyperMerchant#5]
Using HyperMerchant-1.6-dev.jar on Paper-612
Steps to reproduce:
Open shop GUI
Pick up enchanted book (In this instance I used Sharpness 2)
Hold shift
Drop the book directly onto the same enchant in the shop
The shop sells the enchant, but gives an error about buying the enchant because the item is already enchanted, and does not remove the enchant from the item. Allowing you to repeatedly sell your enchant.

**Comment by remremrem** [comment]
Thank you for reporting this somewhat obscure bug. I doubt I would have ever noticed it, and it is a doozy!
Now fixed
