### ISSUE TITLE
Exception while right click on NPCs

### ISSUE THREAD

**Issue by k-jiang** [remremrem/HyperMerchant#6]
> [13:39:59 ERROR]: Could not pass event PlayerInteractEntityEvent to HyperMerchant v1.6-dev
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1531) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
>         at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
> Caused by: java.lang.NullPointerException
> [13:39:59 ERROR]: Could not pass event PlayerInteractEntityEvent to HyperMerchant v1.6-dev
> org.bukkit.event.EventException
>         at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnection.a(PlayerConnection.java:1531) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:68) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PacketPlayInUseEntity.a(SourceFile:12) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_66]
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_66]
>         at net.minecraft.server.v1_9_R2.SystemUtils.a(SourceFile:45) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.D(MinecraftServer.java:726) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.DedicatedServer.D(DedicatedServer.java:399) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.C(MinecraftServer.java:665) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:564) [spigot-survival.jar:git-Spigot-798f32d-0cd0397]
>         at java.lang.Thread.run(Thread.java:745) [?:1.8.0_66]
> Caused by: java.lang.NullPointerException

note that the exception occurs twice at the same time.

tested on:
HyperMerchant 1.6-dev build 30
Spigot 1.9.4 build 849
HyperConomy 0.975.7
Citizens 2.0.18 build 1368

I have BetonQuest installed, dk if it affects. http://betonquest.betoncraft.pl/

**Comment by remremrem** [comment]
Please try latest dev build of HyperMerchant with latest builds of HyperConomy, Citizens, and Bukkit 1.10
